### ISSUE TITLE
duplicate files

### ISSUE THREAD

**Issue by hannesdelbeke** [DaBaptisteFraboul/pistonPluginMaya#1]
seems you duplicated the python files in the icon folder by accident

```
- Piston_UI.py

- Piston_plugin.py
- 📂 icons:
--- Piston_UI.py
--- Piston_plugin.py
```

**Comment by DaBaptisteFraboul** [comment]
Yup, this is an error. I made this repo long ago to train myself while I was learning python for Maya. I will look and merge your patch. 
Thx for the correction
